- hosts: masters
  become: true
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command as a fact
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
- hosts: workers
  become: true
  tasks:
    - name: Remove swap
      shell: swapoff -a

    - name: Join cluster
      shell: "{{ hostvars['master'].join_command }}"
      args:
        chdir: $HOME
        creates: node_joined.txt

